### ISSUE TITLE
Size mismatch in pretrained model

### ISSUE THREAD

**Issue by TinaChen95** [Zain-Jiang/Dict-TTS#3]
Hi, there seems to be a size mismatch in the pretrained model 

When I'm running training from scratch following readme, I got a model with :
dict_encoder.S2PA_module.emb.weight torch.Size([4135, 192])
dict_encoder.S2PA_module.word_emb.weight torch.Size([4500, 192])

but in pretrained model, it is:
dict_encoder.S2PA_module.emb.weight torch.Size([4136, 192])
dict_encoder.S2PA_module.word_emb.weight torch.Size([8000, 192])

And thus I cannot load the pretrained model. What should I do to fix this?
Thanks for reply.

**Comment by bugsz** [comment]
Sorry again for the late reply. We admit that it is our fault and we apologize for it.

1. For the size mismatch of `dict_encoder.S2PA_module.word_emb.weight`: it is caused by the specified word_size `4500` in the inference script is not consistent with our pre-trained model, which is `8000`. We have updated the script, and you can change the script accordingly.
2. For the size mismatch of `dict_encoder.S2PA_module.emb.weight`: it is caused by an update to the text processor, which is located in `data_gen/tts/txt_processors/zh_dict:L53`. We add a special rule `txt = txt.replace("嗯", "恩")` to fix an issue of pypinyin, which makes the generated vocabulary shorter. If you need to infer from the current pretrained checkpoint, you may simply comment this line. We are currently training a newer version of the model, and it will come out soon. 

Thanks for your interest in our work!

**Comment by TinaChen95** [comment]
Great! Looking forward to your new models.
By the way, will you release Cantonese models in the future ?
